spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
  h2:
    console.enabled: true
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
    expiration_time: 15
  mail:
    host: smtp.gmail.com
    port: 587
    username: alperts95@gmail.com
    password: pjfwksevxawpwidb
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true